[versions]
agp = "8.7.1"
kotlin = "2.0.21"
compose-multiplatform = "1.7.0"
navigation-compose = "2.8.0-alpha10"
androidx-activityCompose = "1.9.3"
androidx-core-ktx = "1.13.1"


compose-android-ui = "1.7.5"
compose-android-material3 = "1.3.1"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigation-compose" }

androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }

compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose-android-ui" }

compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose-android-ui" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose-android-ui" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose-android-ui" }


compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-android-material3" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }